### ISSUE TITLE
/info and /ban commands conflict with other bots

### ISSUE THREAD

**Issue by TanyaPegasus** [twohoursonelife/dictator#110]
/info command conflicts with the midjourney bot
/ban command conflicts with built in discord command

This means that sometimes Discord chooses the wrong command from the list if not selected manually, This is especially a problem if there is a delay because you can click on one command just as the delay catches up and they move around. 

Suggestions have been to either rename the commands, or disable the conflicting commands within our server.

**Comment by connorhsm** [comment]
Decided not to move forward with this, I have been informed slash commands are an acceptable nuisance.
