### ISSUE TITLE
Update /ban command to allow additional inputs into the username field

### ISSUE THREAD

**Issue by TanyaPegasus** [twohoursonelife/dictator#111]
When the command was written, discord usernames were intentionally not included as possible input in the username field (limitations within the code are cited, but I don't know more detail. Possibly due to potential clashes?)

Ideally more inputs would be recognised by the bot. The most desired is ability to input a **Discord ID**. 

Other desired inputs are:
Discord ID in <@000000> style format
Mention
Life ID
Discord username in plain text
Discord display name

* Additionally a request to have the bot try '-' if '#' is used in the username field
eg. if /ban user#1234 is attempted, the bot would correct that to /ban user-1234

(Note that currently  "/ban 123234455" (where the numbers are a Discord user ID) behaves like it goes through but doesn't)

New discord.py features relating to the new username format are mentioned here, which may be relevant to code for this issue https://discord.com/channels/336642139381301249/381965829857738772/1117881212527198330

**Comment by connorhsm** [comment]
Need to review all user input commands:

It appears we have 3 necessary variants
_A member like object is: tags, ID, correct discord user or display name_

**Current valid inputs**
- ban, unban
  - 2HOL username
  - Life ID
- whowas
  - Character name (game name)
- info, regenerate
  - Member or like object

**Preferred valid inputs**
- ban, unban, whowas, regenerate, modinfo (new, extended info)
  - Member or like object
  - Character name (game name)
  - 2HOL username
  - Life ID
- info
  - Member or like object

**Comment by connorhsm** [comment]
Not sure if this will be possible as a purely validate function without trialling a DB request.

2HOL username and character name are too similar.

Maybe this needs to look more like:

- ban, unban, regenerate, modinfo (new, extended info)
  - Member or like object
  - Character name (game name)
- whowas
  - 2HOL username
  - Life ID
- info
  - Member or like object
